from fastapi import APIRouter, Depends, HTTPException
from models import SymptomCheckRequest, SymptomCheckResponse
from auth import get_current_user
from config import settings
import json
import requests
from openai import OpenAI

router = APIRouter(prefix="/symptoms", tags=["Symptom Checker"])

# Rule-based fallback symptom expert system
def rule_based_symptom_checker(symptoms: list) -> dict:
    symptoms_lower = [s.lower().strip() for s in symptoms]
    
    # Check for severe emergency symptoms first
    has_emergency = False
    emergency_symptoms = ["chest pain", "shortness of breath", "severe chest pain", "difficulty breathing", "confusion"]
    for es in emergency_symptoms:
        if any(es in s for s in symptoms_lower):
            has_emergency = True
            break
            
    # Compile conditions based on symptoms
    possible_conditions = []
    risk_level = "Low"
    general_advice = "Stay hydrated and get plenty of rest. Monitor your symptoms closely."
    when_to_see_doctor = "Consult a healthcare professional if symptoms persist for more than 3 days or worsen."
    
    if has_emergency:
        risk_level = "High"
        possible_conditions = ["Angina / Myocardial Infarction (Heart Alert)", "Pulmonary Embolism", "Severe Panic Attack", "Pneumonia"]
        general_advice = "Sit in a comfortable position, stay calm, and avoid any physical exertion. Do not take self-medication."
        when_to_see_doctor = "IMMEDIATE EMERGENCY ACTION REQUIRED: Please call emergency services (like 911 or your local ambulance) or go to the nearest emergency room immediately."
    else:
        # Check combinations
        if any(x in s for s in symptoms_lower for x in ["fever", "temperature"]):
            risk_level = "Medium"
            if any(x in s for s in symptoms_lower for x in ["cough", "sore throat"]):
                possible_conditions = ["Influenza (Flu)", "Acute Bronchitis", "Common Cold", "Strep Throat"]
                general_advice = "Rest, drink warm fluids, and gargle with salt water. Consider over-the-counter fever reducers."
                when_to_see_doctor = "See a doctor if fever remains above 102°F (38.9°C) for 3 days or if you develop difficulty swallowing or breathing."
            elif any(x in s for s in symptoms_lower for x in ["vomiting", "nausea"]):
                possible_conditions = ["Gastroenteritis (Stomach Flu)", "Food Poisoning", "Dehydration"]
                general_advice = "Sip clear fluids or oral rehydration salts slowly. Avoid solid foods until vomiting stops."
                when_to_see_doctor = "Seek medical care if you cannot keep fluids down for 24 hours, show signs of dehydration (extreme thirst, dry mouth, dark urine), or have blood in vomit."
            else:
                possible_conditions = ["Viral Infection", "Urinary Tract Infection", "Early Stages of Flu"]
                general_advice = "Monitor body temperature, drink water, and take acetaminophen or ibuprofen if needed."
                when_to_see_doctor = "Consult a doctor if fever is prolonged, accompanied by stiff neck, or severe rash."
        elif any(x in s for s in symptoms_lower for x in ["cough", "sore throat"]):
            possible_conditions = ["Common Cold", "Pharyngitis", "Allergic Rhinitis"]
            general_advice = "Use throat lozenges, stay hydrated with warm water, and use a room humidifier."
            when_to_see_doctor = "See a doctor if you have severe throat pain, difficulty opening your mouth, or a cough lasting over 2 weeks."
        elif any(x in s for s in symptoms_lower for x in ["vomiting", "fatigue", "nausea"]):
            possible_conditions = ["Dehydration", "Fatigue / Exhaustion", "Mild Gastric Irritation"]
            general_advice = "Ensure adequate rest, eat bland foods (BRAT diet: bananas, rice, applesauce, toast), and drink electrolytes."
            when_to_see_doctor = "See a doctor if fatigue is persistent or accompanied by severe abdominal pain."
        else:
            possible_conditions = ["Mild Viral Syndrome", "Tension Headache", "Physical Fatigue / Stress"]
            general_advice = "Ensure 7-8 hours of sleep, manage stress levels, and drink sufficient water."
            when_to_see_doctor = "Consult a doctor if symptoms are persistent or impact daily functionality."
            
    return {
        "possible_conditions": possible_conditions,
        "risk_level": risk_level,
        "general_advice": general_advice,
        "when_to_see_doctor": when_to_see_doctor,
        "disclaimer": "DISCLAIMER: This analysis is generated by an AI assistant for educational purposes only. It is not a formal diagnosis or a replacement for medical professionals. If you are experiencing a medical emergency, please call your local emergency number immediately."
    }

def call_gemini_rest_symptom_checker(symptoms: list) -> dict:
    symptoms_str = ", ".join(symptoms)
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={settings.gemini_api_key}"
    
    prompt = f"""Evaluate these symptoms: {symptoms_str}.
Provide a JSON response representing the medical advice.
Return ONLY a valid JSON object matching the following structure (no markdown formatting, no prefix, just JSON raw string):
{{
  "possible_conditions": ["Condition A", "Condition B", "Condition C"],
  "risk_level": "Low" | "Medium" | "High",
  "general_advice": "Detailed self-care and explanation of symptoms.",
  "when_to_see_doctor": "Description of when to visit or seek emergency care."
}}
Ensure the evaluation is professional, advises consulting a doctor, and flags emergency symptoms if critical.
"""

    payload = {
        "contents": [
            {
                "parts": [
                    {"text": prompt}
                ]
            }
        ]
    }
    response = requests.post(url, json=payload, timeout=25)
    response.raise_for_status()
    res_json = response.json()
    text = res_json['candidates'][0]['content']['parts'][0]['text'].strip()
    
    if text.startswith("```"):
        text = text.split("```")[1]
        if text.startswith("json"):
            text = text[4:]
            
    data = json.loads(text.strip())
    data["disclaimer"] = "DISCLAIMER: This analysis is generated by an AI assistant for educational purposes only. It is not a formal diagnosis or a replacement for medical professionals. If you are experiencing a medical emergency, please call your local emergency number immediately."
    return data

async def call_llm_symptom_checker(symptoms: list) -> dict:
    if settings.gemini_api_key:
        try:
            return call_gemini_rest_symptom_checker(symptoms)
        except Exception as e:
            print(f"Gemini symptom analyzer error: {e}")
            
    if settings.openai_api_key:
        try:
            client = OpenAI(api_key=settings.openai_api_key)
            prompt = f"""Evaluate these symptoms: {", ".join(symptoms)}.
Provide a JSON response representing the medical advice.
Return ONLY a valid JSON object matching the following structure (no markdown, no prefix, just JSON):
{{
  "possible_conditions": ["Condition A", "Condition B"],
  "risk_level": "Low" | "Medium" | "High",
  "general_advice": "Advice",
  "when_to_see_doctor": "When"
}}
"""
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                max_tokens=600,
                response_format={"type": "json_object"}
            )
            data = json.loads(response.choices[0].message.content.strip())
            data["disclaimer"] = "DISCLAIMER: This analysis is generated by an AI assistant for educational purposes only. It is not a formal diagnosis or a replacement for medical professionals. If you are experiencing a medical emergency, please call your local emergency number immediately."
            return data
        except Exception as e:
            print(f"OpenAI symptom analyzer error: {e}")
            
    return rule_based_symptom_checker(symptoms)

@router.post("", response_model=SymptomCheckResponse)
async def check_symptoms(payload: SymptomCheckRequest, current_user: dict = Depends(get_current_user)):
    if not payload.symptoms:
        raise HTTPException(status_code=400, detail="Symptoms list cannot be empty")
        
    analysis = await call_llm_symptom_checker(payload.symptoms)
    
    return SymptomCheckResponse(
        possible_conditions=analysis.get("possible_conditions", ["General Illness"]),
        risk_level=analysis.get("risk_level", "Low"),
        general_advice=analysis.get("general_advice", "Rest and seek medical attention if symptoms persist."),
        when_to_see_doctor=analysis.get("when_to_see_doctor", "Consult a physician at your earliest convenience."),
        disclaimer=analysis.get("disclaimer", "DISCLAIMER: This analysis is for educational purposes only. Consult a doctor for diagnostic help.")
    )
